version: "3"
services:
  react-app:
  image: aarthyramu/devops-build:latest
    container_name: react-app
    ports:
      - "80:80"
container_name: react-app
    restart: unless-stopped
    networks:
      - app-network

  # Production Environment - React App  
  react-app-prod:
    image: aarthyramu/devops-build-prod:latest
    ports:
      - "3000:80"
    container_name: react-app-prod
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
